
import React from 'react'
import './index.css'

function App() {
  return (
    <div className="container">
      <header className="hero">
        <div className="logo-area">
          <div className="logo-circle"></div>
          <h1>Antigravity Browser Fix</h1>
        </div>
        <p className="subtitle">Memorializing the "Connection Reset" Solution</p>
      </header>

      <main>
        <div className="card summary-card">
          <h2>Summary</h2>
          <div className="summary-content">
            <p><strong>The Problem:</strong> Antigravity's browser tool fails with "connection reset" because it prioritizes a broken/restricted system Chrome over the bundled Playwright binaries, often compounded by missing environment variables.</p>
            <p><strong>The Fix:</strong></p>
            <ol>
              <li>Manually install Playwright 1.56.1 binaries.</li>
              <li>Set <code>PLAYWRIGHT_BROWSERS_PATH</code> environment variable.</li>
              <li><strong>Critical Step:</strong> Patch the <code>extension.js</code> file in Antigravity to force usage of the working binary.</li>
              <li>Restart Antigravity.</li>
            </ol>
          </div>
        </div>

        <div className="card deep-dive-card">
          <h2>Deep Dive & Technical Details</h2>
          <p>If the summary didn't solve it, here is the full breakdown of why this happens and how we solved it.</p>

          <div className="step">
            <h3>1. Environment Setup</h3>
            <p>First, ensure the agent has access to the correct binaries.</p>
            <pre><code>npx playwright@1.56.1 install</code></pre>
            <pre><code>[Environment]::SetEnvironmentVariable("PLAYWRIGHT_BROWSERS_PATH", "...", "User")</code></pre>
          </div>

          <div className="step">
            <h3>2. The Root Cause</h3>
            <p>The <code>antigravity-browser-launcher</code> extension has logic to scan for system Chrome installations. On many Windows systems, it finds <code>C:\Program Files\Google\Chrome\Application\chrome.exe</code>. However, when launched by the Agent, this binary often crashes or gets blocked by security policies (UserDataDir), causing the "connection reset".</p>
          </div>

          <div className="step">
            <h3>3. The Definitive Patch</h3>
            <p>We bypassed the scan logic entirely by patching the extension code.</p>
            <p><strong>Target File:</strong> <code>resources/app/extensions/antigravity-browser-launcher/dist/extension.js</code></p>
            <p>We modified the <code>S()</code> function to immediately return our verified binary path:</p>
            <pre><code>S=()=&gt;&#123;return "C:\\Users\\nate\\AppData\\Local\\ms-playwright\\chromium-1194\\chrome-win\\chrome.exe";...&#125;</code></pre>
          </div>
        </div>
      </main>

      <footer>
        <p>Generated by Antigravity Agent • 2026</p>
      </footer>
    </div>
  )
}

export default App
